<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="39755" started-at="2018-03-02T03:20:23Z" finished-at="2018-03-02T03:21:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="39755" started-at="2018-03-02T03:20:23Z" finished-at="2018-03-02T03:21:02Z">
      <class name="sri.srikanth.Buy">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:sri.srikanth.Buy@fe18270]" name="beforeSuite" is-config="true" duration-ms="359" started-at="2018-03-02T08:50:22Z" finished-at="2018-03-02T08:50:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:sri.srikanth.Buy@fe18270]" name="beforeClass" is-config="true" duration-ms="0" started-at="2018-03-02T08:50:23Z" finished-at="2018-03-02T08:50:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:sri.srikanth.Buy@fe18270]" name="beforeMethod" is-config="true" duration-ms="21335" started-at="2018-03-02T08:50:23Z" finished-at="2018-03-02T08:50:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void sri.srikanth.Buy.buy() throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="buy()[pri:0, instance:sri.srikanth.Buy@fe18270]" name="buy" duration-ms="15768" started-at="2018-03-02T08:50:44Z" finished-at="2018-03-02T08:51:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at sri.lib.Util.Logevents(Util.java:187)at sri.Pages.BuyPage.Buy_Search_icon(BuyPage.java:46)at sri.srikanth.Buy.buy(Buy.java:26)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buy -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:sri.srikanth.Buy@fe18270]" name="afterMethod" is-config="true" duration-ms="2542" started-at="2018-03-02T08:51:00Z" finished-at="2018-03-02T08:51:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:sri.srikanth.Buy@fe18270]" name="afterSuite" is-config="true" duration-ms="454" started-at="2018-03-02T08:51:02Z" finished-at="2018-03-02T08:51:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- sri.srikanth.Buy -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
